name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run base workflow
        uses: ./.github/actions/base
        with:
          go-version: '1.24'

      - name: Dependencies
        run: go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@latest

      - name: Build
        run: make release

      - name: Extract changelog
        id: changelog
        run: awk -f ./release_notes.awk ./CHANGELOG.md > release.md

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          bodyFile: release.md
          artifacts: ./dist/*
